### PR TITLE
fix common name verification

### PR DESCRIPTION
**Pull request by benmmurphy**
as far as i can see common name verification does not work in the current version. this fixes it. i'm not sure exactly what tuples can appear in the common name (utf8String,etc) and I'm not sure if my handling of them is correct. but this looks to be an improvement.

### CODE REVIEW

**Comment by deadtrickster** [comment]
Thank you, as you probably can see new tests break R15 support. Nevertheless I love the idea of using real certificates for tests, really full-cycle approach. I hope I can dive into this asap (I hope today or tomorrow).
-  How hard it can be to move dumped certs to file(s)? I think this way we can improve tests readability, what you think?
- You are not sure about CN string encoding right?

**Comment by benmmurphy** [comment]
I'm not too sure about the endian-ness of universalString and bmpString. I'm fairly sure they are utf32 and utf16 (well ucs2 but that is a subset of utf16). i think teletexString is some kind of superset of ASCII. I've seen one cert encoded with this but it just had ASCII characters in it. For teletex/printable I just have an assertion that they only contain ASCII just in case some weirdness happens if someone can put non-ASCII characters in there and we interpret them incorrectly because we are using lists of codepoints in erlang the teletex codepoint would have to match the unicode codepoint which would be unlikely.

**Comment by benmmurphy** [comment]
well apparently universalString and bmpString are both big endian and utf16 and utf32 in erlang are both big endian so that should be ok.

**Comment by deadtrickster** [comment]
Note about `printableString`, looks like it really a subset of ascii. You define it as `C >= 16#20 andalso C =< 16#7E` and if I'm correct for example double-quote (16#22) belongs to this set but it's not valid `printableString` character (http://en.wikipedia.org/wiki/PrintableString http://www.obj-sys.com/asn1tutorial/node10.html <- scroll all the way down here). 

Honestly `teletextString` is a wild animal to me and I hope it is rare case. Also as far as I understand RFC (http://tools.ietf.org/html/rfc5280) prefers Utf8 and Printable strings anyway.

**Comment by benmmurphy** [comment]
I've handled printableString similar to how golang does it: http://golang.org/src/encoding/asn1/asn1.go

**Comment by deadtrickster** [comment]
Well I think this probably can be merged now

**Pull request merged**
